# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36b5834e4aa3bda6301dcfa9cfc6683a2a130312508e19235138ff57f3576295823224959e374965bc5beaf34b0b1b7ec9cad0642d259114cf194c330a6fb780

test:
  secret_key_base: 379b066a4a0c09acffa405fbd70f0e88e88aebe72647afd8b8ce177b24f8c15cf37ed077c299a545a75ae4c7ec19ab0a19494ee68c76dcb71f8ccfaeb7cceab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 379b066a4a0c09acffa405fbd70f0e88e88aebe72647afd8b8ce177b24f8c15cf37ed077c299a545a75ae4c7ec19ab0a19494ee68c76dcb71f8ccfaeb7cceab5
